# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-06 21:48
from __future__ import unicode_literals

import aldryn_translation_tools.models
import app_data.fields
import cms.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active?')),
                ('ordering', models.IntegerField(default=0, verbose_name='ordering')),
                ('content', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='testimonial_content', to='cms.Placeholder')),
                ('thumbnail', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail_testimonial', to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['ordering'],
            },
            bases=(aldryn_translation_tools.models.TranslatedAutoSlugifyMixin, aldryn_translation_tools.models.TranslationHelperMixin, parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TestimonialsConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Type')),
                ('namespace', models.CharField(default=None, max_length=100, unique=True, verbose_name='Instance namespace')),
                ('app_data', app_data.fields.AppDataField(default='{}', editable=False)),
                ('placeholder_testimonial_detail_content', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testimonials_testimonial_content', slotname='testimonial_content', to='cms.Placeholder')),
            ],
            options={
                'verbose_name': 'Testimonials Configuration',
                'verbose_name_plural': 'Testimonials Configurations',
            },
        ),
        migrations.CreateModel(
            name='TestimonialTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(blank=True, db_index=False, help_text='Auto-generated. Used in the URL. If changed, the URL will change. Clear it to have the slug re-created.', max_length=255, verbose_name='slug')),
                ('summary', models.CharField(max_length=2048, verbose_name='summary')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='testimonials.Testimonial')),
            ],
            options={
                'verbose_name': 'Testimonial Translation',
                'db_table': 'testimonials_testimonial_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.AlterUniqueTogether(
            name='testimonialtranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
