# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-06 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='app_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='testimonials.TestimonialsConfig', verbose_name='app configuration'),
        ),
    ]
