# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-06 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from testimonials.models import get_first_app_config


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_testimonial_app_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='app_config',
            field=models.ForeignKey(default=get_first_app_config, null=True, on_delete=django.db.models.deletion.PROTECT, to='testimonials.TestimonialsConfig', verbose_name='app configuration'),
        ),
    ]
