# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-06 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        ('testimonials', '0003_auto_20180807_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialsTeaserCMSPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='+', serialize=False, to='cms.CMSPlugin')),
                ('app_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testimonials.TestimonialsConfig', verbose_name='Apphook configuration')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
