# Generated by Django 2.1.10 on 2019-07-31 12:05

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerticalSpacerPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='bs4_spacer_verticalspacerplugin', serialize=False, to='cms.CMSPlugin')),
                ('smart_space', models.PositiveIntegerField(default=0, help_text='in px, for desktop, height on other devices is calculated automatically', verbose_name='Default Space')),
                ('space_xs', models.PositiveIntegerField(blank=True, default=0, help_text='in px for extra small screens and above', null=True, verbose_name='All screens (default value)')),
                ('space_sm', models.PositiveIntegerField(blank=True, help_text='in px for small screens and above', null=True, verbose_name='small screens and above')),
                ('space_md', models.PositiveIntegerField(blank=True, help_text='in px for medium screens and above', null=True, verbose_name='medium screens and above')),
                ('space_lg', models.PositiveIntegerField(blank=True, help_text='in px for large screens and above', null=True, verbose_name='large screens and above')),
                ('space_xl', models.PositiveIntegerField(blank=True, help_text='in px for extra large screens', null=True, verbose_name='very large screens')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
