# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-03 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerticalSpacerPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='spacer_plugin_verticalspacerplugin', serialize=False, to='cms.CMSPlugin')),
                ('smart_space', models.PositiveIntegerField(default=0, help_text='in px, for desktop, heights on other devices is calculated automatically')),
                ('space_xs', models.PositiveIntegerField(blank=True, default=0, help_text='in px for extra small screens and above', null=True)),
                ('space_sm', models.PositiveIntegerField(blank=True, help_text='in px for small screens and above', null=True)),
                ('space_md', models.PositiveIntegerField(blank=True, help_text='in px for medium screens and above', null=True)),
                ('space_lg', models.PositiveIntegerField(blank=True, help_text='in px for large screens and above', null=True)),
                ('space_xl', models.PositiveIntegerField(blank=True, help_text='in px for extra large screens', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
