# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-07 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import svg_image_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('svg_image_field', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SvgImage',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='svg_image_plugin_svgimage', serialize=False, to='cms.CMSPlugin')),
                ('name', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Image Name')),
                ('max_width', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_height', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('image', svg_image_field.fields.SvgFilerImageField(on_delete=django.db.models.deletion.PROTECT, to='svg_image_field.SvgImageFile')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
