# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-07 22:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svg_image_plugin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='svgimage',
            name='name',
        ),
    ]
