# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-03 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
from .. import models as heading_models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadingPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='heading_plugin_headingplugin', serialize=False, to='cms.CMSPlugin')),
                ('text', models.CharField(default='Heading Text', max_length=2048, null=True)),
                ('heading_tag', enumfields.fields.EnumField(default='h1', enum=heading_models.HeadingTag, max_length=32)),
                ('heading_type', enumfields.fields.EnumField(default='standard', enum=heading_models.HeadingType, max_length=32)),
                ('heading_color', enumfields.fields.EnumField(default='dark', enum=heading_models.HeadingColor, max_length=32)),
                ('heading_alignment', enumfields.fields.EnumField(default='left', enum=heading_models.HeadingAlignment, max_length=32)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
