# Generated by Django 2.1.10 on 2019-07-31 12:04

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='InlineAlignmentModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='bs4_inline_alignment_inlinealignmentmodel', serialize=False, to='cms.CMSPlugin')),
                ('alignment', models.CharField(blank=True, choices=[('left', 'left'), ('center', 'center'), ('right', 'right')], default='left', max_length=256, null=True)),
                ('alignment_sm', models.CharField(blank=True, choices=[('left', 'left'), ('center', 'center'), ('right', 'right')], max_length=256, null=True)),
                ('alignment_md', models.CharField(blank=True, choices=[('left', 'left'), ('center', 'center'), ('right', 'right')], max_length=256, null=True)),
                ('alignment_lg', models.CharField(blank=True, choices=[('left', 'left'), ('center', 'center'), ('right', 'right')], max_length=256, null=True)),
                ('alignment_xl', models.CharField(blank=True, choices=[('left', 'left'), ('center', 'center'), ('right', 'right')], max_length=256, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
