# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-10 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inline_alignment_plugin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inlinealignmentmodel',
            name='alignment_lg',
            field=models.CharField(blank=True, choices=[('left', 'left'), ('center', 'center'), ('right', 'right')], max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='inlinealignmentmodel',
            name='alignment_md',
            field=models.CharField(blank=True, choices=[('left', 'left'), ('center', 'center'), ('right', 'right')], max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='inlinealignmentmodel',
            name='alignment_sm',
            field=models.CharField(blank=True, choices=[('left', 'left'), ('center', 'center'), ('right', 'right')], max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='inlinealignmentmodel',
            name='alignment_xl',
            field=models.CharField(blank=True, choices=[('left', 'left'), ('center', 'center'), ('right', 'right')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='inlinealignmentmodel',
            name='alignment',
            field=models.CharField(blank=True, choices=[('left', 'left'), ('center', 'center'), ('right', 'right')], default='left', max_length=256, null=True),
        ),
    ]
