# Generated by Django 2.1.10 on 2019-07-31 12:04

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bootstrap4HidePluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='bs4_hiding_bootstrap4hidepluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('hide_on_very_small_devices', models.BooleanField(default=False, help_text='hide on very small devices and upwards')),
                ('hide_on_small_devices', models.BooleanField(default=False, help_text='hide on small devices and upwards')),
                ('hide_on_medium_devices', models.BooleanField(default=True, help_text='hide on medium devices and upwards')),
                ('hide_on_large_devices', models.BooleanField(default=False, help_text='hide on large devices and upwards')),
                ('hide_on_very_large_devices', models.BooleanField(default=False, help_text='hide on very large devices')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
