# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-09 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloatModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='float_plugin_floatmodel', serialize=False, to='cms.CMSPlugin')),
                ('float_mode', models.CharField(choices=[('float left', 'left'), ('float right', 'right')], default='float left', max_length=256)),
                ('margin_top', models.PositiveIntegerField(default=0)),
                ('margin_right', models.PositiveIntegerField(default=0)),
                ('margin_bottom', models.PositiveIntegerField(default=0)),
                ('margin_left', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
