# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-09 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('float_plugin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floatmodel',
            name='float_mode',
        ),
        migrations.AddField(
            model_name='floatmodel',
            name='float_breakpoint',
            field=models.CharField(choices=[('xs', 'very small'), ('sm', 'small'), ('md', 'medium'), ('lg', 'large'), ('xl', 'very large')], default='xs', help_text='At which bootstrap4 breakpoint should the float behaviour start, starting from smallest.', max_length=256),
        ),
        migrations.AddField(
            model_name='floatmodel',
            name='float_direction',
            field=models.CharField(choices=[('left', 'float left'), ('right', 'float right')], default='left', max_length=256),
        ),
    ]
