# Generated by Django 2.1.10 on 2019-07-31 12:05

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import backend.plugins.default.heading_element.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadingPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='heading_element_headingplugin', serialize=False, to='cms.CMSPlugin')),
                ('text', models.CharField(max_length=2048)),
                ('heading_tag', enumfields.fields.EnumField(default='h1', enum=backend.plugins.default.heading_element.models.HeadingTag, max_length=32)),
                ('heading_color', enumfields.fields.EnumField(default='dark', enum=backend.plugins.default.heading_element.models.HeadingColor, max_length=32)),
                ('heading_alignment', enumfields.fields.EnumField(default='left', enum=backend.plugins.default.heading_element.models.HeadingAlignment, max_length=32)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
