# Generated by Django 2.2.11 on 2020-05-01 07:52

import aldryn_translation_tools.models
import app_data.fields
import backend.articles.models.article
import backend.articles.models.plugins.article_list
import cms.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import enumfields.fields
import filer.fields.image
import parler.fields
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='is published?')),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now, help_text="Doesn't influence the publication time, used in sorting of the articles")),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
            bases=(aldryn_translation_tools.models.TranslatedAutoSlugifyMixin, aldryn_translation_tools.models.TranslationHelperMixin, parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ArticlesConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Type')),
                ('namespace', models.CharField(default=None, max_length=100, unique=True, verbose_name='Instance namespace')),
                ('app_data', app_data.fields.AppDataField(default='{}', editable=False)),
                ('verbose_name', models.CharField(blank=True, max_length=100, null=True)),
                ('placeholder_article_detail_content', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_content', slotname='article_content', to='cms.Placeholder')),
            ],
            options={
                'verbose_name': 'Articles Configuration',
                'verbose_name_plural': 'Articles Configurations',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_config', models.ForeignKey(default=backend.articles.models.article.get_first_app_config, null=True, on_delete=django.db.models.deletion.PROTECT, to='articles.ArticlesConfig', verbose_name='app configuration')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
            bases=(aldryn_translation_tools.models.TranslatedAutoSlugifyMixin, aldryn_translation_tools.models.TranslationHelperMixin, parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ArticleListPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='articles_articlelistpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('limit', enumfields.fields.EnumField(default=0, enum=backend.articles.models.plugins.article_list.Limit, help_text='Optional', max_length=10, verbose_name='Articles limit')),
                ('app_config', models.ForeignKey(default=backend.articles.models.article.get_first_app_config, on_delete=django.db.models.deletion.PROTECT, to='articles.ArticlesConfig', verbose_name='App configuration')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ArticleLinkModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='articles_articlelinkmodel', serialize=False, to='cms.CMSPlugin')),
                ('name', models.CharField(max_length=2048)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='articles.Article')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AddField(
            model_name='article',
            name='app_config',
            field=models.ForeignKey(default=backend.articles.models.article.get_first_app_config, null=True, on_delete=django.db.models.deletion.PROTECT, to='articles.ArticlesConfig', verbose_name='app configuration'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='articles.Category'),
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='article_content', to='cms.Placeholder'),
        ),
        migrations.AddField(
            model_name='article',
            name='teaser_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teaser_image', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(blank=True, db_index=False, help_text='Auto-generated. Used in the URL. If changed, the URL will change. Clear it to have the slug re-created.', max_length=255, verbose_name='slug')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='articles.Category')),
            ],
            options={
                'verbose_name': 'category Translation',
                'db_table': 'articles_category_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ArticleTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(blank=True, db_index=False, help_text='Auto-generated. Used in the URL. If changed, the URL will change. Clear it to have the slug re-created.', max_length=255, verbose_name='slug')),
                ('teaser_description', models.TextField(blank=True, verbose_name='description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='articles.Article')),
            ],
            options={
                'verbose_name': 'Article Translation',
                'db_table': 'articles_article_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
