# Generated by Django 2.1.14 on 2019-11-11 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_add_default_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_show_darkening_filter_under_main_menu',
        ),
    ]
