# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-24 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import src.section_plugin.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='section_plugin_sectionplugin', serialize=False, to='cms.CMSPlugin')),
                ('name', models.CharField(default='No name', help_text='This name wont show up in the frontend, it shows on the plugin only for better orientation', max_length=2048, null=True)),
                ('max_width', enumfields.fields.EnumField(default='1280', enum=src.section_plugin.models.MaxWidth, max_length=32)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
