# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-11 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        ('hide_plugin', '0002_auto_20160720_0346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bootstrap4HidePluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='hide_plugin_bootstrap4hidepluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('hide_on_very_small_devices', models.BooleanField(default=False, help_text='hide on very small devices and upwards')),
                ('hide_on_small_devices', models.BooleanField(default=False, help_text='hide on small devices and upwards')),
                ('hide_on_medium_devices', models.BooleanField(default=True, help_text='hide on medium devices and upwards')),
                ('hide_on_large_devices', models.BooleanField(default=False, help_text='hide on large devices and upwards')),
                ('hide_on_very_large_devices', models.BooleanField(default=False, help_text='hide on very large devices')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.RemoveField(
            model_name='hidepluginmodel',
            name='cmsplugin_ptr',
        ),
        migrations.DeleteModel(
            name='HidePluginModel',
        ),
    ]
