# Generated by Django 2.1.10 on 2019-07-31 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LightboxGalleryCmsPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='bs4_lightbox_gallery_lightboxgallerycmsplugin', serialize=False, to='cms.CMSPlugin')),
                ('thumbnail_size', models.CharField(blank=True, choices=[('50x50', 'Small (50px)'), ('100x100', 'Medium (100px)'), ('150x150', 'Big (150px)')], default='50x50', max_length=256, null=True)),
                ('justify', models.CharField(blank=True, choices=[('justify-content-left', 'Justify left'), ('justify-content-center', 'Justify center'), ('justify-content-right', 'Justify right')], default='justify-content-left', max_length=256, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='LightboxGalleryItemCmsPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='bs4_lightbox_gallery_lightboxgalleryitemcmsplugin', serialize=False, to='cms.CMSPlugin')),
                ('caption', models.CharField(max_length=255)),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
